name: Run tests

# on: pull_request

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Fix containers auth
        run: |
          sudo mkdir -p "$(dirname /run/containers/30002/auth.json)"
          sudo echo {} > /run/containers/30002/auth.json
          sudo chmod a+rx /run/containers
          sudo chmod a+r /run/containers/30002/auth.json
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: direnv-nix
        uses: JRMurr/direnv-nix-action@v4.2.0
      - name: run tests
        run: just test
        shell: bash
